### ISSUE TITLE
Warp10 is not available at 8080 port

### ISSUE THREAD

**Issue by savelmtr** [senx/warp10-docker#114]
Hello everyone! I'm trying to test Warp10. Now I've set it up in docker container. Also I've generated all needed tokens. But when I try to make a request (an http one), I get a connection error.
Here is my docker-compose:
```
version: '3.7'

services:
  warp10:
    image: warp10io/warp10:latest
    restart: always
    volumes:
      - 'warp10_data:/data'
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      - WARP10_HEAP=3g
      - WARP10_HEAP_MAX=3g
volumes:
  warp10_data:
```
Here is my request in pycharm:
```
POST http://localhost:8080/api/v0/update
Content-Type: text/plain
X-Warp10-Token: 7JFFkgL6wcJT39pOrljslq_.zPasxlye_aVdWA0ufQge4LvJH29yEH7M9PzhmtERxC.I8MQhrEerTJyRVHvIzh3IgR8f1kW63mfoZDiIIL7

1// test{} 42
```
Here is response in pycharm:
```
POST http://localhost:8080/api/v0/update

org.apache.http.NoHttpResponseException: localhost:8080 failed to respond
```
Here is my request in python (for thouse who like python syntax):
```
r = requests.post(
    'http://host.docker.internal:8080/api/v0/update',
    headers={'Content-Type': 'text/plain', 'X-Warp10-Token': '7JFFkgL6wcJT39pOrljslq_.zPasxlye_aVdWA0ufQge4LvJH29yEH7M9PzhmtERxC.I8MQhrEerTJyRVHvIzh3IgR8f1kW63mfoZDiIIL7'},
    data='''
    1380475081000000// foo{label0=val0,label1=val1} 123
    '''.encode('utf8')
)
r.text
```
And here is python's traceback (short version):
```
ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

So, people, what am I doing wrong?
